import { NextRequest, NextResponse } from "next/server";
import { getGitHubClient } from "@/lib/github";

export async function POST(req: NextRequest) {
  const { repoName } = await req.json();

  if (!repoName)
    return NextResponse.json({ error: "Missing repoName" }, { status: 400 });

  try {
    const octokit = await getGitHubClient();

    const { data: user } = await octokit.rest.users.getAuthenticated();
    const username = user.login;

    const response = await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      private: false,
      description: "Generated by AI Project Builder",
    });

    return NextResponse.json({ success: true, repo: response.data });
  } catch (err: any) {
    return NextResponse.json(
      { error: err.message || "GitHub error" },
      { status: 500 }
    );
  }
}
