name: Deploy Qwintly to GCP Cloud Run

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  SERVICE_NAME: qwintly
  REGION: us-central1
  GAR_REPOSITORY: qwintly-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker auth
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build container
        run: |
          SUPABASE_URL="${{ vars.NEXT_PUBLIC_SUPABASE_URL }}"
          SUPABASE_PUBLISHABLE_KEY="${{ vars.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}"

          echo "::add-mask::$SUPABASE_URL"
          echo "::add-mask::$SUPABASE_PUBLISHABLE_KEY"
          echo "::add-mask::${{ secrets.NEXT_PUBLIC_GA_ID }}"

          docker build \
            --build-arg NEXT_PUBLIC_SUPABASE_URL="$SUPABASE_URL" \
            --build-arg NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY="$SUPABASE_PUBLISHABLE_KEY" \
            --build-arg NEXT_PUBLIC_GA_ID="${{ secrets.NEXT_PUBLIC_GA_ID }}" \
            --build-arg NEXT_PUBLIC_SITE_URL="${{ vars.NEXT_PUBLIC_SITE_URL }}" \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .

      - name: Push container
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --service-account=${{ secrets.RUNTIME_SERVICE_ACCOUNT }} \
            --allow-unauthenticated \
            --set-env-vars=NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }},NEXT_PUBLIC_SITE_URL=${{ vars.NEXT_PUBLIC_SITE_URL }},NEXT_PUBLIC_SUPABASE_URL=${{vars.NEXT_PUBLIC_SUPABASE_URL}},NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${{vars.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}},UPSTASH_REDIS_REST_URL_GEN_EVENTS=${{vars.UPSTASH_REDIS_REST_URL_GEN_EVENTS}},PUBSUB_TOPIC_WEB_GEN=${{vars.PUBSUB_TOPIC_WEB_GEN}} \
            --set-secrets=GEMINI_API_KEY=gemini-api-key:latest,UPSTASH_REDIS_REST_TOKEN_GEN_EVENTS=upstash-redis-rest-token-gen-events:latest
